# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/leo/Delivery/OOP/ARCADE/B-OOP-400-BDX-4-1-arcade-leopold.sallan-gemard

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/leo/Delivery/OOP/ARCADE/B-OOP-400-BDX-4-1-arcade-leopold.sallan-gemard

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leo/Delivery/OOP/ARCADE/B-OOP-400-BDX-4-1-arcade-leopold.sallan-gemard/CMakeFiles /home/leo/Delivery/OOP/ARCADE/B-OOP-400-BDX-4-1-arcade-leopold.sallan-gemard//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leo/Delivery/OOP/ARCADE/B-OOP-400-BDX-4-1-arcade-leopold.sallan-gemard/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arcade

# Build rule for target.
arcade: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arcade
.PHONY : arcade

# fast build rule for target.
arcade/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/build
.PHONY : arcade/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named games

# Build rule for target.
games: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 games
.PHONY : games

# fast build rule for target.
games/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/games.dir/build.make CMakeFiles/games.dir/build
.PHONY : games/fast

#=============================================================================
# Target rules for targets named graphicals

# Build rule for target.
graphicals: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graphicals
.PHONY : graphicals

# fast build rule for target.
graphicals/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicals.dir/build.make CMakeFiles/graphicals.dir/build
.PHONY : graphicals/fast

#=============================================================================
# Target rules for targets named arcade_nibbler

# Build rule for target.
arcade_nibbler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arcade_nibbler
.PHONY : arcade_nibbler

# fast build rule for target.
arcade_nibbler/fast:
	$(MAKE) $(MAKESILENT) -f Games/Nibbler/CMakeFiles/arcade_nibbler.dir/build.make Games/Nibbler/CMakeFiles/arcade_nibbler.dir/build
.PHONY : arcade_nibbler/fast

#=============================================================================
# Target rules for targets named arcade_pacman

# Build rule for target.
arcade_pacman: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arcade_pacman
.PHONY : arcade_pacman

# fast build rule for target.
arcade_pacman/fast:
	$(MAKE) $(MAKESILENT) -f Games/PacMan/CMakeFiles/arcade_pacman.dir/build.make Games/PacMan/CMakeFiles/arcade_pacman.dir/build
.PHONY : arcade_pacman/fast

#=============================================================================
# Target rules for targets named arcade_sdl2

# Build rule for target.
arcade_sdl2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arcade_sdl2
.PHONY : arcade_sdl2

# fast build rule for target.
arcade_sdl2/fast:
	$(MAKE) $(MAKESILENT) -f Graphicals/SDL2/CMakeFiles/arcade_sdl2.dir/build.make Graphicals/SDL2/CMakeFiles/arcade_sdl2.dir/build
.PHONY : arcade_sdl2/fast

#=============================================================================
# Target rules for targets named arcade_ncurses

# Build rule for target.
arcade_ncurses: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arcade_ncurses
.PHONY : arcade_ncurses

# fast build rule for target.
arcade_ncurses/fast:
	$(MAKE) $(MAKESILENT) -f Graphicals/nCurses/CMakeFiles/arcade_ncurses.dir/build.make Graphicals/nCurses/CMakeFiles/arcade_ncurses.dir/build
.PHONY : arcade_ncurses/fast

Core/src/core.o: Core/src/core.cpp.o
.PHONY : Core/src/core.o

# target to build an object file
Core/src/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/Core/src/core.cpp.o
.PHONY : Core/src/core.cpp.o

Core/src/core.i: Core/src/core.cpp.i
.PHONY : Core/src/core.i

# target to preprocess a source file
Core/src/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/Core/src/core.cpp.i
.PHONY : Core/src/core.cpp.i

Core/src/core.s: Core/src/core.cpp.s
.PHONY : Core/src/core.s

# target to generate assembly for a file
Core/src/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/Core/src/core.cpp.s
.PHONY : Core/src/core.cpp.s

Core/src/libWrapper.o: Core/src/libWrapper.cpp.o
.PHONY : Core/src/libWrapper.o

# target to build an object file
Core/src/libWrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/Core/src/libWrapper.cpp.o
.PHONY : Core/src/libWrapper.cpp.o

Core/src/libWrapper.i: Core/src/libWrapper.cpp.i
.PHONY : Core/src/libWrapper.i

# target to preprocess a source file
Core/src/libWrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/Core/src/libWrapper.cpp.i
.PHONY : Core/src/libWrapper.cpp.i

Core/src/libWrapper.s: Core/src/libWrapper.cpp.s
.PHONY : Core/src/libWrapper.s

# target to generate assembly for a file
Core/src/libWrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/Core/src/libWrapper.cpp.s
.PHONY : Core/src/libWrapper.cpp.s

Core/src/main.o: Core/src/main.cpp.o
.PHONY : Core/src/main.o

# target to build an object file
Core/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/Core/src/main.cpp.o
.PHONY : Core/src/main.cpp.o

Core/src/main.i: Core/src/main.cpp.i
.PHONY : Core/src/main.i

# target to preprocess a source file
Core/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/Core/src/main.cpp.i
.PHONY : Core/src/main.cpp.i

Core/src/main.s: Core/src/main.cpp.s
.PHONY : Core/src/main.s

# target to generate assembly for a file
Core/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/Core/src/main.cpp.s
.PHONY : Core/src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... core"
	@echo "... games"
	@echo "... graphicals"
	@echo "... arcade"
	@echo "... arcade_ncurses"
	@echo "... arcade_nibbler"
	@echo "... arcade_pacman"
	@echo "... arcade_sdl2"
	@echo "... Core/src/core.o"
	@echo "... Core/src/core.i"
	@echo "... Core/src/core.s"
	@echo "... Core/src/libWrapper.o"
	@echo "... Core/src/libWrapper.i"
	@echo "... Core/src/libWrapper.s"
	@echo "... Core/src/main.o"
	@echo "... Core/src/main.i"
	@echo "... Core/src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

